version: 1
bots:
- name: support_bot
  token_env: TELEGRAM_BOT_TOKEN_SUPPORT
  channels: [telegram]
  allowed_user_ids: [123456789]
  active: true
  provider_defaults:
    chat: openai_default
    slides: glm_default
- name: ops_bot
  token_env: TELEGRAM_BOT_TOKEN_OPS
  channels: [telegram]
  allowed_user_ids: [123456789]
  active: true
  provider_defaults:
    deploy: shell_default
    tests: shell_default
